---

- name: install prereq packages
  ansible.builtin.apt:
    name:
      - build-essential
      - dkms
    state: present

- name: get VirtualBox version.
  ansible.builtin.slurp:
    src: /home/{{ local_account_username }}/.vbox_version
  register: get_virtualbox_version

- name: set VirtualBox version.
  ansible.builtin.set_fact:
    virtualbox_version: "{{ get_virtualbox_version['content'] | b64decode }}"

- name: mount VirtualBox guest additions ISO.
  ansible.posix.mount:
    name: /tmp/vbox
    src: "/home/{{ local_account_username }}/VBoxGuestAdditions_{{ virtualbox_version }}.iso"
    opts: loop
    state: mounted
    fstype: iso9660

- name: run VirtualBox guest additions installation.
  ansible.builtin.shell: sh /tmp/vbox/VBoxLinuxAdditions.run
  changed_when: false
  failed_when: false

- name: unmount VirtualBox guest additions ISO.
  ansible.posix.mount:
    name: /tmp/vbox
    src: "/home/{{ local_account_username }}/VBoxGuestAdditions_{{ virtualbox_version }}.iso"
    state: absent
    fstype: iso9660

- name: delete VirtualBox guest additions ISO.
  ansible.builtin.file:
    path: "/home/{{ local_account_username }}/VBoxGuestAdditions_{{ virtualbox_version }}.iso"
    state: absent
