---
dependency:
  name: galaxy
  options:
    requirements-file: molecule/vagrant/requirements.yml

driver:
  name: vagrant
  provider:
    name: virtualbox

platforms:
  - name: instance
    box: ${MOLECULE_VAGRANT_BOX:-generic/debian12}
    memory: 2048
    cpus: 2
    provider_raw_config_args:
      - "customize ['modifyvm', :id, '--nictype1', 'virtio']"
    instance_raw_config_args:
      - "vm.provision 'shell', inline: 'sudo apt-get update -y && sudo apt-get install -y python3'"

provisioner:
  name: ansible
  config_options:
    defaults:
      interpreter_python: auto_silent
      callback_whitelist: profile_tasks
      stdout_callback: yaml
  inventory:
    host_vars:
      instance:
        ansible_user: vagrant
        ansible_become: true
  playbooks:
    converge: ${MOLECULE_SCENARIO_DIRECTORY}/converge.yml

verifier:
  name: ansible

scenario:
  name: vagrant
  test_sequence:
    - dependency
    - syntax
    - create
    - prepare
    - converge
    - idempotence
    - verify
    - destroy
