---
dependency:
  name: galaxy
  options:
    requirements-file: molecule/default/requirements.yml

driver:
  name: docker

platforms:
  - name: instance
    image: ${MOLECULE_DISTRO:-debian:12}
    dockerfile: Dockerfile.j2
    pre_build_image: false
    privileged: true
    cgroupns_mode: host
    command: /sbin/init
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:rw
      - /tmp
      - /run
    tmpfs:
      - /tmp:exec,mode=1777
      - /run:exec,mode=755
      - /run/lock:noexec,nosuid,nodev,mode=1777
    capabilities:
      - SYS_ADMIN
      - SYS_RESOURCE
      - NET_ADMIN
    security_opts:
      - seccomp=unconfined
      - apparmor=unconfined
    environment:
      container: docker
      SYSTEMD_UNIT_PATH: /etc/systemd/system
    memory: 2g
    memory_swap: 2g
    keep_volumes: false
    tty: true

provisioner:
  name: ansible
  config_options:
    defaults:
      interpreter_python: auto_silent
      stdout_callback: yaml
      bin_ansible_callbacks: true
      gathering: smart
      fact_caching: memory
      host_key_checking: false
      retry_files_enabled: false
    ssh_connection:
      pipelining: true
  inventory:
    host_vars:
      instance:
        ansible_user: root
        ansible_python_interpreter: /usr/bin/python3
        ansible_connection: docker
  env:
    ANSIBLE_CONFIG: ${MOLECULE_SCENARIO_DIRECTORY}/ansible.cfg
    ANSIBLE_ROLES_PATH: ${MOLECULE_PROJECT_DIRECTORY}/..
    ANSIBLE_HOST_KEY_CHECKING: false
    ANSIBLE_FORCE_COLOR: true
    ANSIBLE_REMOTE_TMP: /tmp
    ANSIBLE_LOCAL_TEMP: /tmp
  playbooks:
    prepare: ${MOLECULE_SCENARIO_DIRECTORY}/prepare.yml
    converge: ${MOLECULE_SCENARIO_DIRECTORY}/converge.yml
    verify: ${MOLECULE_SCENARIO_DIRECTORY}/verify.yml
  ansible_args:
    - --diff
    - -v
    - --timeout=60
  timeout: 600

verifier:
  name: ansible

scenario:
  name: default
  create_sequence:
    - dependency
    - create
    - prepare
  converge_sequence:
    - dependency
    - create
    - prepare
    - converge
  test_sequence:
    - dependency
    - cleanup
    - destroy
    - syntax
    - create
    - prepare
    - converge
    - idempotence
    - verify
    - cleanup
    - destroy
